version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package...".
      - zip -r build.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws --version
      - aws configure set region us-east-2
      - pwd
      - aws s3 cp s3://devopswithlasantha.tech assets images index.html
      - aws lambda update-function-code --function-name VisitorCount --zip-file fileb://build.zip
      - echo "DONE!!"